
# ORGANISATION
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mohammadAli
spec:
  memberOf: [platform]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
spec:
  type: team
  children: []
